export const BASE_URL = 'https://www.demo609.amrithaa.com/backend-cema/public/api/';

export const API_ENPOINTS = {
    SLIDER : 'getSlider',
    COUNTRIES : 'countries',
    STATES : 'states',
    CITIES : 'city',
    ADD_REVIEW : 'add_review',
    GET_WISHLIST : 'get_wishlist',
    ADD_REMOVE_WISHLIST_ARRAY : 'add_remove_wishlist_array',
    ADD_REMOVE_WISHLIST : 'add_remove_wishlist',
    BRANDS : 'brands',
    ADD_TO_CART_ARRAY : 'addToCartArray',
    ADD_TO_CART : 'addToCart',
    UPDATE_CART_QUANTITY : 'updateCartQuantity',
    GET_CART : 'getCartData',
    REMOVE_FROM_CART : 'removeFromCart',
    CHECKOUT : 'checkout',
    GET_PRODUCTS : 'products',
    APPLY_COUPAN : 'apply-coupan',
    REMOVE_COUPAN : 'remove-coupan',
    ORDERS : 'orders',
    CATEGORIES : 'categories',
    HOME_FIRST_CATEGORIES : 'homeFirstcategories',
    HOME_SECOND_CATEGORIES : 'homeSecondcategories',
    NAV_CATEGORIES : 'navCategories',
    SUB_CATEGORIES : 'subcategories',
    CHILD_CATEGORIES : 'childcategories',
    CATEGORY_DETAILS : 'category',
    SUB_CATEGORY_DETAILS : 'subcategory',
    CHILD_CATEGORY_DETAILS : 'childcategory',
    MY_PROFILE_DETAILS : 'myprofile',
    UPDATE_PROFILE_DETAILS : 'update/profile',
    CREATE_ADDRESS : 'create-address',
    GET_SHIIPPING_ADDRESS : 'manageaddress',
    GET_BILLING_ADDRESS : 'billing-address',
    CREATE_BILLING_ADDRESS : 'create-billing-address',
    CHANGE_PASSWORD : 'password/change',
    CREATE_PASSWORD : 'password/create',
    LOGIN : 'login',
    REGISTER : 'register',
    VERIFY_REGISTRATION : 'verify_register',
    RESEND_TWO_FACTOR : 'resend_two_factor_code',
    FORGET_PASSWORD: 'password/create',
    NOTIFICATION  : 'notifications',
    TRACK_ORDER : 'track/order',
    GET_ALL_ADDRESS : 'getAllAddress',
    GET_ALL_BILLING_ADDRESS : 'getAllBillingAddress',
    CREATE_SHIPPING_ADDRESS: 'create-address',
    UPDATE_SHIPPING_ADDRESS : 'update-shipping-address',
    UPDATE_CART_QUANTITY: 'updateCartQuantity',
    ALL_REVIEW_LISTING : 'reviews'
}